### ISSUE TITLE
How to contact the author and how to install this?

### ISSUE THREAD

**Issue by elnath78** [ESOUIMods/ESOUIMods.github.io#1]
Hello,

The only installation guide that I found is not up to date:
https://www.esoui.com/forums/faq.php?faq=install#faq_howto_install

The ESO default installation path is now "\Zenimax Online\The Elder Scrolls Online" under Programs folder and there is no "live" subfolder. I read the author said he cannot have a .exe or a website for financial limitations, I think I could help with both, I found no e-mail or other means to contact the current author, but hopefully he will read this. Message in a bottle sent! :-)

**Comment by Sharlikran** [comment]
A GitHub repository isn't a way to contact anyone for support for general questions. Please use ESOUI in the future.

I have my own website for personal use. Originally it was a way to tell some friends on the xEdit discord what to buy if they wanted to play. Then I needed it for Master Merchant documentation. So this really is not a way to ask for support on how to do anything with the game.

The main way to install mods is to use [Minion](https://www.minion.gg/) and if you could not understand that FAQ I would suggest you get Minion working.

> The ESO default installation path is now "\Zenimax Online\The Elder Scrolls Online" under Programs folder

In the FAQ it does not say to go to the install folder for the game as you mentioned. That is where the program files are located. 

> PC:
> C:\Users\< username >\Documents\Elder Scrolls Online\live\AddOns\< AddOn A FolderName >\< files >
> Mac:
> ~/Documents/Elder Scrolls Online/live/AddOns/< AddOn A FolderName >/< files >

The FAQ tells you to go to the Documents folder and they add some symbols `<>` to indicate that it will be different for each person. As an example they put a folder name as `< username >` because you need to know what your own user name is on your PC or Mac. Same with some of the other folders like `\< AddOn A FolderName >` which just means any folder name like `HarvestMap`.

![image](https://user-images.githubusercontent.com/1912426/168777267-0c408c7a-0ba5-4ab5-9f77-75a51d5c4faf.png)

Use the link above or just click the main link on ESOUI to download and install Minion it would be easier for you most likely and it's what I use anyway so I know when there are updates to mods.

**Comment by Sharlikran** [comment]
Although I may, when I have time add some kind of installation instructions. Especially since High Isle will be out next month.

**Comment by elnath78** [comment]
> A GitHub repository isn't a way to contact anyone for support for general questions. Please use ESOUI in the future.

Unfortunately there is no way to contact anyone on esoui website as well.

> The main way to install mods is to use [Minion](https://www.minion.gg/) and if you could not understand that FAQ I would suggest you get Minion working.

I installed it manually eventually.
